Add config validation PR check
This check ensures the example workspace configs under the examples directory (used by tutorials) are valid. The check does uncover a WRF config that needs to be updated.

Signed-off-by: Lin Guo <linsword13@gmail.com>

diff --git a/share/ramble/cloud-build/ramble-pr-software-conflicts.yaml b/share/ramble/cloud-build/ramble-pr-software-conflicts.yaml
--- a/share/ramble/cloud-build/ramble-pr-software-conflicts.yaml
+++ b/share/ramble/cloud-build/ramble-pr-software-conflicts.yaml
@@ -55,6 +55,10 @@ steps:
         # https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
         conflict_err=$$?
 
+        ramble python share/ramble/qa/check_configs.py
+        configs_err=$$?
+
+        error=0
         if [ $$conflict_err -gt 0 ]; then
           echo " ***** Conflicts in software definitions detected."
           error=1
@@ -62,6 +66,11 @@ steps:
 
         # $$ characters are required for cloud-build:
         # https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
+        if [ $$configs_err -gt 0 ]; then
+          echo " ***** One or more workspace configurations failed validation."
+          error=1
+        fi
+
         exit $$error
     id: ramble-style-tests
     entrypoint: /bin/bash
